packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - lefthook

catalog:
  "@biomejs/biome": 2.3.14
  "@cloudflare/vitest-pool-workers": 0.12.1
  "@hono/zod-openapi": 1.2.1
  "@types/node": 25.0.3
  "@vitest/coverage-v8": 3.2.0
  jwt-decode: 4.0.0
  knip: 5.83.0
  rimraf: 6.1.2
  tsx: 4.21.0
  typescript: 5.9.3
  vitest: 3.2.0
  wrangler: 4.63.0
  zod: 4.3.5
