/**
 * Auth0 User Sync Script
 *
 * Fetches all users from Auth0 Management API and upserts them into D1.
 * Generates a seed-users.sql file that can be applied locally or in CI.
 *
 * Usage: cd apps/api && varlock run -- npx tsx scripts/sync-auth0-users.ts
 *
 * Env vars required (via varlock):
 *   AUTH0_DOMAIN, AUTH0_CLIENT_USER_MANAGEMENT_ID, AUTH0_CLIENT_USER_MANAGEMENT_SECRET
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

function requireEnv(key: string): string {
  const value = process.env[key];
  if (!value) throw new Error(`Missing required env var: ${key}`);
  return value;
}

const AUTH0_DOMAIN = requireEnv('AUTH0_DOMAIN');
const AUTH0_CLIENT_USER_MANAGEMENT_ID = requireEnv('AUTH0_CLIENT_USER_MANAGEMENT_ID');
const AUTH0_CLIENT_USER_MANAGEMENT_SECRET = requireEnv('AUTH0_CLIENT_USER_MANAGEMENT_SECRET');

function log(message: string): void {
  // biome-ignore lint/suspicious/noConsole: CLI script
  console.info(message);
}

function logError(message: string): void {
  // biome-ignore lint/suspicious/noConsole: CLI script
  console.error(message);
}

interface Auth0User {
  user_id: string;
  nickname: string;
  picture: string;
  created_at: string;
  updated_at: string;
}

interface TokenResponse {
  access_token: string;
  token_type: string;
}

async function getManagementToken(): Promise<string> {
  const response = await fetch(`https://${AUTH0_DOMAIN}/oauth/token`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      client_id: AUTH0_CLIENT_USER_MANAGEMENT_ID,
      client_secret: AUTH0_CLIENT_USER_MANAGEMENT_SECRET,
      audience: `https://${AUTH0_DOMAIN}/api/v2/`,
      grant_type: 'client_credentials',
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Failed to get management token: ${response.status} ${text}`);
  }

  const data = (await response.json()) as TokenResponse;
  return data.access_token;
}

async function fetchAllUsers(token: string): Promise<Auth0User[]> {
  const allUsers: Auth0User[] = [];
  let page = 0;
  const perPage = 100;

  while (true) {
    const url = new URL(`https://${AUTH0_DOMAIN}/api/v2/users`);
    url.searchParams.set('page', String(page));
    url.searchParams.set('per_page', String(perPage));
    url.searchParams.set('fields', 'user_id,nickname,picture,created_at,updated_at');
    url.searchParams.set('include_fields', 'true');

    // biome-ignore lint/performance/noAwaitInLoops: sequential pagination required by Auth0 API
    const response = await fetch(url.toString(), {
      headers: { authorization: `Bearer ${token}` },
    });

    if (!response.ok) {
      const text = await response.text();
      throw new Error(`Failed to fetch users (page ${String(page)}): ${response.status} ${text}`);
    }

    const users = (await response.json()) as Auth0User[];
    if (users.length === 0) break;

    allUsers.push(...users);
    if (users.length < perPage) break;
    page++;
  }

  return allUsers;
}

function escapeSQL(value: string): string {
  return value.replace(/'/g, "''");
}

function generateSQL(users: Auth0User[]): string {
  const lines: string[] = [
    '-- Generated by sync-auth0-users.ts',
    `-- ${String(users.length)} users from Auth0 (${AUTH0_DOMAIN})`,
    `-- Generated at ${new Date().toISOString()}`,
    '',
  ];

  for (const user of users) {
    const auth0Sub = escapeSQL(user.user_id);
    const nickname = escapeSQL(user.nickname);
    const picture = escapeSQL(user.picture);
    const createdAt = escapeSQL(user.created_at);
    const updatedAt = escapeSQL(user.updated_at);

    lines.push(
      `INSERT INTO users (auth0_sub, nickname, picture, created_at, updated_at)`,
      `  VALUES ('${auth0Sub}', '${nickname}', '${picture}', '${createdAt}', '${updatedAt}')`,
      `  ON CONFLICT (auth0_sub) DO UPDATE SET`,
      `    nickname = excluded.nickname,`,
      `    picture = excluded.picture,`,
      `    updated_at = excluded.updated_at;`,
    );
  }

  return lines.join('\n');
}

async function main(): Promise<void> {
  log('Fetching Auth0 management token...');
  const token = await getManagementToken();

  log('Fetching users from Auth0...');
  const users = await fetchAllUsers(token);
  log(`Found ${String(users.length)} users`);

  const sql = generateSQL(users);
  const outputPath = resolve(import.meta.dirname, '..', 'data/seed-users.sql');
  writeFileSync(outputPath, sql);
  log(`Written to ${outputPath}`);

  log('Done. Apply with:');
  log('  npx wrangler d1 execute downtown65-db --local --file data/seed-users.sql');
}

main().catch((err: unknown) => {
  logError(String(err));
  process.exit(1);
});
